# Generated by Django 4.1.5 on 2023-01-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
