# Generated by Django 4.1.5 on 2023-02-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
