# Generated by Django 4.1.5 on 2023-01-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='token',
            field=models.BigIntegerField(auto_created=True, default=34567),
            preserve_default=False,
        ),
    ]
