# Generated by Django 4.1.5 on 2023-01-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_logs_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='token',
            field=models.PositiveIntegerField(auto_created=True),
        ),
    ]
