# Generated by Django 4.1.5 on 2023-01-27 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_logs_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='token',
        ),
    ]
