# Generated by Django 4.1.5 on 2023-01-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_user_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='token',
            field=models.PositiveIntegerField(auto_created=True, default=100),
            preserve_default=False,
        ),
    ]
