# Generated by Django 4.1.5 on 2023-01-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_logs_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='has_logged_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logs',
            name='token',
            field=models.PositiveIntegerField(auto_created=True, unique=True),
        ),
    ]
